import Link from 'next/link';
import { ArrowRight, Building2, GraduationCap, Landmark, ShieldCheck, Users } from 'lucide-react';

const roles = [
  { title: 'Citizen', subtitle: 'Report a local challenge', href: '/login/citizen', icon: Users, colour: 'bg-[#e9f8e7] text-[#176144]' },
  { title: 'Government Admin', subtitle: 'Review and route challenges', href: '/login/government', icon: Landmark, colour: 'bg-[#e8f2fb] text-[#275f93]' },
  { title: 'University', subtitle: 'Develop applied solutions', href: '/login/university', icon: GraduationCap, colour: 'bg-[#f3edff] text-[#6946a7]' },
  { title: 'Industry / CSR', subtitle: 'Fund measurable impact', href: '/login/industry', icon: Building2, colour: 'bg-[#fff4e5] text-[#a76217]' },
];
export default function Landing() { return <main className="min-h-screen overflow-hidden bg-mist"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-moss text-xl font-black text-lime">S</div><div><p className="text-xl font-black tracking-tight">SAHAAY</p><p className="text-xs font-medium text-slate-500">Societal Innovation Portal</p></div></div><span className="hidden items-center gap-2 text-sm font-semibold text-moss sm:flex"><ShieldCheck className="h-4 w-4"/> Collaborative public service</span></header><section className="mx-auto grid max-w-7xl gap-10 px-5 py-12 md:py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="mb-4 text-sm font-bold uppercase tracking-[.18em] text-moss">A unified innovation ecosystem</p><h1 className="max-w-3xl text-4xl font-black leading-[1.06] tracking-tight md:text-6xl">One challenge.<br/><span className="text-moss">Many collaborators.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-600">SAHAAY connects citizens reporting societal challenges with government, universities and industry/CSR partners—so practical local problems become coordinated solutions.</p><div className="mt-8 flex items-center gap-3 text-sm font-semibold text-slate-600"><span className="h-px w-10 bg-moss"/> Choose your portal to continue</div></div><div className="relative"><div className="absolute -inset-5 -z-0 rounded-[2.5rem] bg-lime/40 blur-2xl"/><div className="relative grid gap-3 sm:grid-cols-2">{roles.map(({title,subtitle,href,icon:Icon,colour})=><Link key={title} href={href} className="card group min-h-44 p-5 transition hover:-translate-y-1 hover:shadow-lg"><div className={`mb-7 grid h-11 w-11 place-items-center rounded-xl ${colour}`}><Icon className="h-5 w-5"/></div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p><span className="mt-4 flex items-center gap-1 text-sm font-bold text-moss">Enter portal <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>)}</div></div></section><footer className="mx-auto max-w-7xl px-5 py-8 text-xs text-slate-500">© {new Date().getFullYear()} SAHAAY · Building impact through collaboration.</footer></main>; }
